live_config_reload = true

import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[debug]
render_timer = false

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "0x009688"
text = "0xffffff"

[font]
size = 12

[font.bold]
family = "Cousine Nerd Font"
style = "Bold"

[font.italic]
family = "Cousine Nerd Font"
style = "Italic"

[font.normal]
family = "Cousine Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 2

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.95
padding = { x = 0, y = 0 }
dynamic_padding = true
dimensions = { columns = 0, lines = 0}
