#!/usr/bin/env bash
set -e

# command line tools
#sudo xcode-select --install

# homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install mas
brew install cask
brew tap cjbassi/gotop

brew bundle
